Makefile
backend/src/main/resources/application.yaml
backend/src/main/resources/db/changelog/changesets/1_initial_schema.sql
backend/src/main/resources/db/changelog/db.changelog-master.yaml

feat: configuration liquibase

---

.gitignore
Makefile
frontend/src/app/routes/__root.tsx

fix: remove devtools from production build

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/UserController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/User.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/dto/GetMeResponse.kt

feat(GetMeResponse): add fullName field and change example of username

---

Makefile
frontend/src/app/routes/__root.tsx

fix: remove TanStack Devtools

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/LoggingAspectConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/SecurityConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/annotaion/Loggable.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/security/RequestIdFilter.kt
backend/src/main/resources/logback.xml

- Implemented logging aspect using Spring AOP to handle method execution logging.
- Added `logback.xml` configuration for logging output customization.
- Adjusted Swagger annotations to correctly describe the response objects for ProductController endpoints

feat(logging): add Spring AOP for logging and configure logback

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/SwaggerConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/Team.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TeamRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/TeamRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TeamResponse.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamControllerTest.kt

- Implemented Post, Put, Get, and GetAll methods in TeamController, with GetAll supporting pagination.
- Added tests for the new methods

feat(TeamController): add Post, Put, Get, and GetAll mappings

---

Makefile
frontend/src/shared/components/data-table.tsx
frontend/src/shared/locales/en/common.json

fix(data-table): extract strings to l11n

---

Makefile
frontend/src/widgets/create-product-dialog/ui/dialog.tsx

fix(create-product): dialog locale keys

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamMeetingController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/TeamMeeting.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/enums/TeamMeetingType.kt
backend/src/main/kotlin/com/jellyone/zadachnik/exception/ControllerExceptionHandler.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TeamMeetingRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamMeetingService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/TeamMeetingRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TeamMeetingResponse.kt
backend/src/main/resources/db/changelog/changesets/3_change_team_meeting_title.sql
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamMeetingControllerTest.kt

- Added 409 Conflict Status Code with same ticker
- Added tests for the new methods

feat(TeamMeetingController): add post mapping

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/SwaggerConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TaskController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/Task.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/TaskChange.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TaskChangeRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TaskRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskChangeService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/TaskRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TaskChangeResponse.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TaskResponse.kt
backend/src/main/resources/db/changelog/changesets/4_change_value_task_changes.sql
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TaskControllerTest.kt

- Added tests for the new methods

feat(TaskController): add Post, Get, Put endpoints

---

Makefile
backend/build.gradle.kts

feat(JaCoCo): configure plugin for test coverage reporting

---

.github/workflows/ci.yaml

ci: add jacoco report step

---

.github/workflows/cd.yaml
ansible/staging.yaml
docker-compose.yaml

cd: use github sha as version

---

traefik/traefik.yaml

fix(Traefik): configuration typo

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductControllerTest.kt

feat: implement `GET` all tasks for product

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/SwaggerConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ArticleController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamMeetingController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/Article.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/TeamMeeting.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ArticleRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ArticleService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamMeetingService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/CreateArticleRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/UpdateArticleRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/ArticleResponse.kt
backend/src/main/resources/db/changelog/changesets/9_add_team_meeting_field_to_article.sql
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamMeetingControllerTest.kt

feat: implement `POST` and  `PUT` articles

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TaskController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamMeetingController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/Comment.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/CommentRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ArticleService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/CommentService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/CreateCommentRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/CommentResponse.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TaskControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamMeetingControllerTest.kt

feat: implement `GET` and `POST` for comment (article, task)

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ArticleController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TaskController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/Task.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/enums/TaskType.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskChangeService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/TaskRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TaskResponse.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TaskControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamMeetingControllerTest.kt

feat: implement `GET article by id` and create TaskType enum

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/ProductTeamRelation.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TaskRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskService.kt
backend/src/main/resources/db/changelog/changesets/10_add_status_field_product_teams_table.sql
backend/src/main/resources/db/changelog/changesets/91_recreate_product_teams_table.sql
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TaskControllerTest.kt

feat: implement `GET` all team tasks

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/SwaggerConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/ProductTeamRelation.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductsInvitationsService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/UpdateProductInvitationRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/ProductTeamRelationResponse.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsControllerTest.kt

feat: implement `POST`,`GET`,`PUT` methods for products invitations

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/configuration/SwaggerConfig.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamsInvitationsController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/UserTeamRelation.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/UserTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamsInvitationsService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/UpdateTeamInvitationRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/UserTeamInvitationResponse.kt
backend/src/main/resources/db/changelog/changesets/92_create_user_team_table.sql
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamsInvitationsControllerTest.kt

feat: implement `POST`,`GET`,`PUT` methods for teams invitations

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductService.kt

fix: sorting by TaskStatus

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductReleasesController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/Article.kt
backend/src/main/kotlin/com/jellyone/zadachnik/domain/ProductRelease.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductReleaseRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ArticleService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductReleaseService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/CreateProductReleaseRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/request/TaskToReleaseRequest.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/ArticleResponse.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/ProductReleaseResponse.kt
backend/src/main/resources/db/changelog/changesets/93_add_m_to_m_and_version_field_release_table.sql
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductReleasesControllerTest.kt

feat: implement `POST` and `GET` methods for products releases

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/UserController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/UserTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductsInvitationsService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamsInvitationsService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamsInvitationsControllerTest.kt

feat: implement `GET` methods for users in team and teams in product

---

Makefile
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/app/App.tsx
frontend/src/app/layout/layout.tsx
frontend/src/app/routes/_authenticated/products/$productId/issues.tsx
frontend/src/entities/task/api.ts
frontend/src/entities/task/index.ts
frontend/src/entities/task/model.ts
frontend/src/entities/task/ui/create-dialog.tsx
frontend/src/entities/task/ui/select-type.tsx
frontend/src/shared/api.gen.ts
frontend/src/shared/locales/en/task.json
frontend/src/widgets/kanban-board/index.ts
frontend/src/widgets/kanban-board/ui/board.tsx

feat: tasks creation, drag-n-drop

---

Makefile
frontend/src/app/routes/_authenticated/products/$productId/tasks.$taskId.tsx
frontend/src/entities/task/api.ts
frontend/src/entities/task/model.ts
frontend/src/shared/locales/en/task.json

feat: task comments

---

Makefile
frontend/src/app/routes/_authenticated/products/$productId/tasks.$taskId.tsx
frontend/src/entities/task/index.ts
frontend/src/entities/task/ui/select-task-status.tsx
frontend/src/entities/task/ui/status-logic.tsx
frontend/src/entities/task/ui/task-description.tsx
frontend/src/entities/task/ui/task-status-badge.tsx
frontend/src/shared/components/ui/select.tsx
frontend/src/shared/locales/en/task.json

feat: task edit

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ArticleController.kt
frontend/src/app/routes/_authenticated/products/$productId/releases.$releaseId.tsx
frontend/src/app/routes/_authenticated/products/$productId/tasks.$taskId.tsx
frontend/src/entities/article/api.ts
frontend/src/entities/article/index.ts
frontend/src/entities/article/model.ts
frontend/src/entities/article/ui/article-comments.tsx
frontend/src/entities/article/ui/article-content.tsx
frontend/src/entities/comment/index.ts
frontend/src/entities/comment/model.ts
frontend/src/entities/comment/ui/comment.tsx
frontend/src/entities/task/api.ts
frontend/src/entities/task/model.ts
frontend/src/shared/api.gen.ts
frontend/src/shared/components/ui/editor.tsx

feat: release notes content & comments

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/domain/TeamMeeting.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TeamMeetingResponse.kt
backend/src/main/resources/db/changelog/changesets/94_delete_team_meeting_table.sql

chore: delete users-field from TeamMeeting

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/UserTeamInvitationResponse.kt

Add user field to team invintation response

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/ProductTeamRelationResponse.kt

feat: add team and product for ProductTeamRelationResponse

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductsInvitationsService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsControllerTest.kt

feat: add getAllTeamProductInvitations endpoint

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamsInvitationsController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/UserTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductsInvitationsService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamsInvitationsService.kt

feat: update getAllTeamInvitationByTeamId endpoint

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/ProductController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/ProductsInvitationsService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductsInvitationsControllerTest.kt

feat: create getAllProductInvitationByProductId endpoint

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/UserController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/UserTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamsInvitationsService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamsInvitationsControllerTest.kt

feat: create getAllTeamInvitationsForUser endpoint

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/CommentRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/CommentService.kt

feat: create getMinutesByTeamId endpoint

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/SprintController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/SprintRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/SprintService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/SprintControllerTest.kt

feat: create getSprintsByProductId endpoint

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamMeetingController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TeamMeetingRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamMeetingService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TeamMeetingResponse.kt
frontend/src/app/App.tsx
frontend/src/app/routes/_authenticated/teams/$teamId/meetings.tsx
frontend/src/entities/article/api.ts
frontend/src/entities/meeting/api.ts
frontend/src/entities/meeting/index.ts
frontend/src/entities/meeting/model.ts
frontend/src/entities/meeting/ui/table.tsx
frontend/src/shared/api.gen.ts
frontend/src/shared/locales/en/meeting.json

feat: team meetings page

---

Makefile
frontend/src/app/routes/_authenticated/me/index.tsx
frontend/src/app/routes/_authenticated/teams/$teamId/index.tsx
frontend/src/entities/principal/api.ts
frontend/src/entities/team/api.ts
frontend/src/entities/team/index.ts
frontend/src/entities/team/ui/pending-invitations.tsx
frontend/src/entities/team/ui/team-participants.tsx
frontend/src/shared/api.gen.ts
frontend/src/shared/hooks/use-dialog.tsx

feat(frontend): team invitations

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TeamMeetingRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamMeetingService.kt

fix(backend): getMeetingsByTeamId

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/UserController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/UserTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamsInvitationsService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamControllerTest.kt

fix(backend): change getTeamsOfCurrentUser implementation

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/controller/TeamMeetingController.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ArticleRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TeamMeetingService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TeamMeetingWithArticles.kt

feat: add articles field to TeamMeetingWithArticles dto

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskChangeService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/web/response/TaskChangeResponse.kt

feat: add STATUS and ASSIGNEE_USERNAME type of field for TaskChangeLogs

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskChangeService.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskService.kt

feat: remove logs after creation task entity

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/repository/ProductTeamRelationRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/repository/UserTeamRelationRepository.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/ProductControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TeamControllerTest.kt

fix(backend): product and team owner add to get requests

---

Makefile
backend/src/main/kotlin/com/jellyone/zadachnik/repository/TaskRepository.kt
backend/src/main/kotlin/com/jellyone/zadachnik/service/TaskService.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/SprintControllerTest.kt
backend/src/test/kotlin/com/jellyone/zadachnik/controller/TaskControllerTest.kt

fix(backend): taskStatus field should be enum in sql-query

---

Makefile
frontend/src/app/routes/_authenticated/products/$productId/tasks.$taskId.tsx
frontend/src/entities/article/api.ts
frontend/src/entities/article/ui/article-comments.tsx
frontend/src/entities/task/api.ts
frontend/src/shared/api.gen.ts

fix(frontend/comments): reset comment field after send

---

Makefile
frontend/src/entities/principal/ui/sidebar.tsx
frontend/src/shared/api.gen.ts
frontend/src/shared/components/app-sidebar.tsx

fix(frontend): remove meeting notification

---

Makefile
frontend/src/app/routes/_authenticated/products/$productId/index.tsx
frontend/src/entities/product/api.ts
frontend/src/entities/product/ui/products-table.tsx

fix: remove issues percent
